language: node_js
node_js: '9'

before_script:
        - npm install && cd Assets && npm install && cd ../Users && npm install

env:
        - NODE_ENV=test

services:
        - mongodb

script:
        - npm test

after_script:
        - killall node
